'use strict';
const KEY='ethan-admission-preview-v2';
const LEGACY='ethan-admission-preview-v1';
const $=s=>document.querySelector(s);
function load(){try{const value=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(LEGACY)||'null');return value&&typeof value==='object'&&!Array.isArray(value)?value:null}catch{return null}}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el}
function download(data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=(data.reference||'ETHAN-application')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const labels={name:'Full name',email:'Email',phone:'Phone',category:'Category',ageGroup:'Age group',location:'City / state',guardian:'Guardian',guardianPhone:'Guardian phone',relationship:'Relationship',programme:'Programme',mode:'Learning mode',experience:'Experience',schedule:'Schedule',goals:'Learning goals'};
function summary(data){const dl=node('dl');for(const [key,label] of Object.entries(labels)){if(!data[key])continue;dl.append(node('dt',label),node('dd',key==='ageGroup'?(data[key]==='under18'?'Under 18':'18 or above'):data[key]))}return dl}
const menu=$('#menu-toggle');menu?.addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
if($('#cards')){
 const params=new URLSearchParams(location.search);$('#audience').value=params.get('audience')||'';
 for(const area of [...new Set(PROGRAMMES.map(p=>p.area))])$('#area').add(new Option(area,area));
 function render(){const q=$('#search').value.trim().toLowerCase();const area=$('#area').value;const audience=$('#audience').value;const matches=PROGRAMMES.filter(p=>(!area||p.area===area)&&(!audience||p.audience===audience)&&[p.title,p.description,...p.topics].join(' ').toLowerCase().includes(q));$('#cards').replaceChildren();$('#result-count').textContent=matches.length+' of '+PROGRAMMES.length+' digital programmes';for(const p of matches){const card=node('article',undefined,'card');card.append(node('span',p.area,'tag'),node('h3',p.title),node('p',p.description),node('p','Suggested audience: '+p.audience,'muted'));const b=node('button','View programme','secondary');b.onclick=()=>{const target=$('#programme-details');target.replaceChildren(node('p',p.area,'eyebrow'),node('h2',p.title),node('p',p.description),node('h3','What you could learn'));const ul=node('ul');p.topics.forEach(t=>ul.append(node('li',t)));target.append(ul,node('p','Availability, duration, fees and entry requirements: confirm with admissions.','muted'));const a=node('a','Choose this programme →','button');a.href='apply.html?programme='+encodeURIComponent(p.title);target.append(a);$('#programme-dialog').showModal()};card.append(b);$('#cards').append(card)}if(!matches.length)$('#cards').append(node('p','No matches. Try another search or clear the filters.'))}
 ['search','area','audience'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#close-dialog').onclick=()=>$('#programme-dialog').close();render();
}
const form=$('#application');
if(form){
 const select=$('#programme');select.add(new Option('Choose programme',''));PROGRAMMES.forEach(p=>select.add(new Option(p.title,p.title)));
 const saved=load();if(saved)for(const [name,value] of Object.entries(saved)){const input=form.elements.namedItem(name);if(input){if(input.type==='checkbox')input.checked=value==='on';else input.value=value}}
 const requested=new URLSearchParams(location.search).get('programme');if(PROGRAMMES.some(p=>p.title===requested))select.value=requested;
 let step=0;
 function guardian(){const required=form.elements.ageGroup.value==='under18';$('#guardian-fields').hidden=!required;for(const name of ['guardian','guardianPhone','relationship','guardianConsent']){const input=form.elements.namedItem(name);input.required=required;input.disabled=!required}}
 form.elements.ageGroup.addEventListener('change',guardian);guardian();
 function data(){return Object.fromEntries(new FormData(form))}
 function display(){$('#submission-options').replaceChildren();document.querySelectorAll('[data-step]').forEach(el=>el.hidden=Number(el.dataset.step)!==step);document.querySelectorAll('.wizard-tabs li').forEach((el,i)=>{el.classList.toggle('active',i===step);if(i===step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current')});$('#back').hidden=step===0;$('#next').hidden=step===2;$('#finish').hidden=step!==2;if(step===2)$('#review').replaceChildren(summary(data()));$('#feedback').textContent=''}
 function valid(index,report=true){for(const el of form.querySelector('[data-step="'+index+'"]').querySelectorAll('input,select,textarea'))if(!el.disabled&&!el.checkValidity()){if(report)el.reportValidity();return false}return true}
 $('#next').onclick=()=>{if(valid(step)){step++;display();form.querySelector('[data-step="'+step+'"] legend').scrollIntoView({block:'center'})}};
 $('#back').onclick=()=>{step--;display()};
 function save(reviewed){const previous=load();const entry={...data(),reviewConsent:reviewed,reference:previous?.reference||'EDA-'+(globalThis.crypto?.randomUUID?.()||String(Date.now())).toUpperCase(),savedAt:new Date().toISOString(),state:reviewed?'Ready to send — receipt pending':'Draft — not submitted'};let stored=true;try{localStorage.setItem(KEY,JSON.stringify(entry))}catch{stored=false}$('#feedback').textContent=reviewed?(stored?'Application ready. Choose a channel below, then press Send in the app that opens.':'Application ready. Browser storage is unavailable; copy your application before leaving this page.'):(stored?'Draft saved on this device.':'Unable to save. Browser storage may be unavailable.');$('#submission-options').replaceChildren();if(reviewed)$('#submission-options').append(submissionPanel(entry));}
 $('#save-draft').onclick=()=>save(false);
 form.addEventListener('submit',e=>{e.preventDefault();for(let i=0;i<3;i++){if(!valid(i,false)){step=i;display();valid(i);return}}save(true)});display();
}
if($('#saved')){const target=$('#saved');function renderSaved(){const data=load();target.replaceChildren();if(!data){const empty=node('article',undefined,'card');empty.append(node('h2','Your journey starts here.'),node('p','No local draft is saved in this browser.'));const a=node('a','Prepare an application','button');a.href='apply.html';empty.append(a);target.append(empty);return}const card=node('article',undefined,'card');card.append(node('span',data.state||'Draft — not submitted','badge'),node('h2',data.programme||'Programme not selected'),node('p','Reference: '+(data.reference||'Local draft')),node('p','Last saved: '+new Date(data.savedAt).toLocaleString()),summary(data));const actions=node('div',undefined,'actions');const edit=node('a','Continue editing','button');edit.href='apply.html';const dl=node('button','Download copy','secondary');dl.onclick=()=>download(data);const print=node('button','Print / Save as PDF','secondary');print.onclick=()=>window.print();const del=node('button','Delete local draft','secondary');del.onclick=()=>{if(confirm('Delete the application draft saved in this browser?')){try{localStorage.removeItem(KEY);localStorage.removeItem(LEGACY);renderSaved()}catch{target.append(node('p','Unable to delete. Browser storage may be unavailable.'))}}};actions.append(edit,dl,print,del);card.append(actions);if(data.reviewConsent&&AdmissionSubmission.ready(data))card.append(submissionPanel(data));else card.append(node('p','Use Continue editing to review your details and confirm sharing before sending your application.','muted'));target.append(card)}renderSaved()}
$('#enquiry')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const message='Hello Ethan Digital Academy, my name is '+data.get('name')+'.\nTopic: '+data.get('topic')+'\n'+data.get('message');const result=$('#enquiry-result');result.replaceChildren();const a=node('a','Open WhatsApp to review and send','button');a.href='https://wa.me/2348064656499?text='+encodeURIComponent(message);a.target='_blank';a.rel='noopener noreferrer';result.append(a)});

function submissionPanel(data){
 const panel=node('section',undefined,'card submission-panel');const routes=AdmissionSubmission.links(data);
 panel.append(node('h2','Send your application'),node('p','Choose a channel, review the completed message and press Send. Opening the message does not confirm submission. Admissions will acknowledge receipt.'));
 const actions=node('div',undefined,'actions');
 for(const [label,href] of [['Submit via WhatsApp',routes.whatsapp],['Submit via Email',routes.email]]){const a=node('a',label,'button');a.href=href;if(href.startsWith('https:')){a.target='_blank';a.rel='noopener noreferrer'}actions.append(a)}
 const copy=node('button','Copy application message','secondary');copy.type='button';const status=node('p',undefined,'muted');status.setAttribute('role','status');
 const details=node('details');details.append(node('summary','View or manually copy the application message'));const text=node('textarea');text.value=routes.text;text.readOnly=true;text.rows=12;text.setAttribute('aria-label','Complete application message');details.append(text);
 copy.onclick=async()=>{try{await navigator.clipboard.writeText(routes.text);status.textContent='Application message copied. Paste it into your message and press Send.'}catch{details.open=true;text.focus();text.select();status.textContent='Select and copy the message below, then paste it into WhatsApp or email.'}};
 actions.append(copy);panel.append(actions,status,details,node('p','WhatsApp: +234 806 465 6499 · Email: ethandigitalacademy@gmail.com','wrap muted'));return panel;
}
